export const STATUS_COLORS: Record<string, string> = {
  active: 'success',
  trial: 'brand',
  frozen: 'warning',
  archived: 'gray',
  paid: 'success',
  pending: 'warning',
  overdue: 'danger',
  refunded: 'gray',
  new: 'brand',
  contacted: 'cyan',
  negotiation: 'accent',
  won: 'success',
  lost: 'danger',
  todo: 'gray',
  in_progress: 'brand',
  review: 'accent',
  done: 'success',
  low: 'gray',
  medium: 'brand',
  high: 'warning',
  urgent: 'danger',
  on_leave: 'warning',
  inactive: 'gray',
  planned: 'accent',
  completed: 'gray',
  present: 'success',
  absent: 'danger',
  late: 'warning',
  excused: 'gray',
};

export const colorForStatus = (status: string): string => STATUS_COLORS[status] ?? 'gray';
