export const ROUTES = {
    root: '/',
    auth: {
        login: '/auth/login',
        register: '/auth/register',
        forgotPassword: '/auth/forgot-password',
        otp: '/auth/otp',
    },
    dashboard: '/dashboard',
    students: '/students',
    studentDetails: (id) => `/students/${id}`,
    groups: '/groups',
    groupDetails: (id) => `/groups/${id}`,
    teachers: '/teachers',
    payments: '/payments',
    leads: '/leads',
    attendance: '/attendance',
    tasks: '/tasks',
    calendar: '/calendar',
    reports: '/reports',
    notifications: '/notifications',
    settings: '/settings',
    activityLog: '/activity',
};
